/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperadminSetupRouteImport } from './routes/superadmin-setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as RegisterUserRouteImport } from './routes/register.user'
import { Route as RegisterLibraryRouteImport } from './routes/register.library'
import { Route as CategoriesSlugRouteImport } from './routes/categories/$slug'
import { Route as BooksSlugRouteImport } from './routes/books/$slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBookshopsRouteImport } from './routes/admin/bookshops'
import { Route as AdminBooksRouteImport } from './routes/admin/books'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersIdRouteImport } from './routes/account/orders/$id'

const SuperadminSetupRoute = SuperadminSetupRouteImport.update({
  id: '/superadmin-setup',
  path: '/superadmin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterUserRoute = RegisterUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => RegisterRoute,
} as any)
const RegisterLibraryRoute = RegisterLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => RegisterRoute,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookshopsRoute = AdminBookshopsRouteImport.update({
  id: '/bookshops',
  path: '/bookshops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/account/orders/$id',
  path: '/account/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/register': typeof RegisterRouteWithChildren
  '/superadmin-setup': typeof SuperadminSetupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/bookshops': typeof AdminBookshopsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/register/library': typeof RegisterLibraryRoute
  '/register/user': typeof RegisterUserRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/register': typeof RegisterRouteWithChildren
  '/superadmin-setup': typeof SuperadminSetupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/bookshops': typeof AdminBookshopsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/register/library': typeof RegisterLibraryRoute
  '/register/user': typeof RegisterUserRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/books': typeof BooksIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/register': typeof RegisterRouteWithChildren
  '/superadmin-setup': typeof SuperadminSetupRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/bookshops': typeof AdminBookshopsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/books/$slug': typeof BooksSlugRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/register/library': typeof RegisterLibraryRoute
  '/register/user': typeof RegisterUserRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/books/': typeof BooksIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/register'
    | '/superadmin-setup'
    | '/admin/applications'
    | '/admin/books'
    | '/admin/bookshops'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/books/$slug'
    | '/categories/$slug'
    | '/register/library'
    | '/register/user'
    | '/account/'
    | '/admin/'
    | '/books/'
    | '/categories/'
    | '/account/orders/$id'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/register'
    | '/superadmin-setup'
    | '/admin/applications'
    | '/admin/books'
    | '/admin/bookshops'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/books/$slug'
    | '/categories/$slug'
    | '/register/library'
    | '/register/user'
    | '/account'
    | '/admin'
    | '/books'
    | '/categories'
    | '/account/orders/$id'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/register'
    | '/superadmin-setup'
    | '/admin/applications'
    | '/admin/books'
    | '/admin/bookshops'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/books/$slug'
    | '/categories/$slug'
    | '/register/library'
    | '/register/user'
    | '/account/'
    | '/admin/'
    | '/books/'
    | '/categories/'
    | '/account/orders/$id'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  RegisterRoute: typeof RegisterRouteWithChildren
  SuperadminSetupRoute: typeof SuperadminSetupRoute
  BooksSlugRoute: typeof BooksSlugRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/superadmin-setup': {
      id: '/superadmin-setup'
      path: '/superadmin-setup'
      fullPath: '/superadmin-setup'
      preLoaderRoute: typeof SuperadminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/user': {
      id: '/register/user'
      path: '/user'
      fullPath: '/register/user'
      preLoaderRoute: typeof RegisterUserRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/register/library': {
      id: '/register/library'
      path: '/library'
      fullPath: '/register/library'
      preLoaderRoute: typeof RegisterLibraryRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookshops': {
      id: '/admin/bookshops'
      path: '/bookshops'
      fullPath: '/admin/bookshops'
      preLoaderRoute: typeof AdminBookshopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminBookshopsRoute: typeof AdminBookshopsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminBookshopsRoute: AdminBookshopsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface RegisterRouteChildren {
  RegisterLibraryRoute: typeof RegisterLibraryRoute
  RegisterUserRoute: typeof RegisterUserRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterLibraryRoute: RegisterLibraryRoute,
  RegisterUserRoute: RegisterUserRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  RegisterRoute: RegisterRouteWithChildren,
  SuperadminSetupRoute: SuperadminSetupRoute,
  BooksSlugRoute: BooksSlugRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
